# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Tony.Ko's Blog
tagline:          'Learning Journey'
description:      'A roadmap which records how to learn the program.'
url:              
baseurl:          /hyde/

author:
  name:           'Tony Ko'
  url:            https://twitter.com/tainenko
  email:          tainenko@gmail.com

paginate:         5

# Custom vars
version:          2.1.0

plugins: [jekyll-paginate, jekyll-gist]

github:
  repo:           https://github.com/tainenko/hyde
